namespace Testura.Android.Util
{
    public enum DependencyHandling
    {
        InstallIfMissing,
        AlwaysInstall,
        NeverInstall
    }

    public enum AttributeTags
    {
        TextContains,
        Text,
        ResourceId,
        ContentDesc,
        Class,
        Package,
        Index
    }

    public enum SwipeDirections
    {
        Left,
        Up,
        Right,
        Down
    }

    public enum State
    {
        Enable,
        Disable
    }

    public enum KeyEvents
    {
        Unknown,
        Menu,
        SoftRight,
        Home,
        Back,
        Call,
        Endcall,
        Number0,
        Number1,
        Number2,
        Number3,
        Number4,
        Number5,
        Number6,
        Number7,
        Number8,
        Number9,
        Star,
        Pound,
        DpadUp,
        DpadDown,
        DpadLeft,
        DpadRight,
        DpadCenter,
        VolumeUp,
        VolumeDown,
        Power,
        Camera,
        Clear,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Comma,
        Period,
        AltLeft,
        AltRight,
        ShiftLeft,
        ShiftRight,
        Tab,
        Space,
        Sym,
        Explorer,
        Envelope,
        Enter,
        Del,
        Grave,
        Minus,
        Equals,
        LeftBracket,
        RightBracket,
        Backslash,
        Semicolon,
        Apostrophe,
        Slash,
        At,
        Num,
        Headsethook,
        Focus,
        Plus,
        Menu2,
        Notification,
        Search,
        TagLastKeycode
    }
}